"""agentplane-core: shared contract — Definition schema, registry models, interfaces."""

from a2a.types import AgentCapabilities, AgentCard, AgentInterface, AgentSkill

from agentplane_core.card_json import agent_card_from_dict, agent_card_to_json_dict
from agentplane_core.definition import (
    DEPRECATED_NODE_VERSIONS,
    NODE_CATALOG,
    SCHEMA_VERSION,
    Edge,
    EndNode,
    EndNodeConfig,
    ExposeConfig,
    FlowDefinition,
    Layout,
    LayoutPosition,
    LlmCallNode,
    LlmCallNodeConfig,
    McpToolNode,
    McpToolNodeConfig,
    Node,
    RetrievalNode,
    RetrievalNodeConfig,
    RouterInputType,
    RouterNode,
    RouterNodeConfig,
    RouterRule,
    StartNode,
    StartNodeConfig,
    TemplateNode,
    TemplateNodeConfig,
    input_ports,
    output_ports,
    ports_compatible,
    prompt_variables,
    single_required_string_input,
)
from agentplane_core.interfaces import ScoredHit, SearchBackend, SecretsProvider, VectorStore
from agentplane_core.registry import (
    AuthMode,
    Capabilities,
    Card,
    DefinitionInfo,
    DefinitionStatus,
    DeploymentInfo,
    EntryKind,
    HealthStatus,
    Page,
    RegistryEntry,
    RegistryEntryCreate,
    RegistryEntryPatch,
    SearchQuery,
    Severity,
    ToolCard,
    ToolCardTool,
    ValidationIssue,
    ValidationResult,
    serialize_card,
)
from agentplane_core.resources import (
    SECRET_PLACEHOLDER,
    VECTOR_DB_KINDS,
    EmbeddingConfig,
    McpServerResource,
    ModelProviderResource,
    Resource,
    ResourceKind,
    VectorDBResource,
)
from agentplane_core.types import (
    Document,
    JsonObject,
    JsonSchema,
    PortType,
    render_documents,
    split_port_ref,
)
from agentplane_core.validation import ErrorCode, validate_structure

__version__ = "0.0.1"

__all__ = [
    "DEPRECATED_NODE_VERSIONS",
    "NODE_CATALOG",
    "SCHEMA_VERSION",
    "SECRET_PLACEHOLDER",
    "VECTOR_DB_KINDS",
    "AgentCapabilities",
    "AgentCard",
    "AgentInterface",
    "AgentSkill",
    "AuthMode",
    "Capabilities",
    "Card",
    "DefinitionInfo",
    "DefinitionStatus",
    "DeploymentInfo",
    "Document",
    "Edge",
    "EmbeddingConfig",
    "EndNode",
    "EndNodeConfig",
    "EntryKind",
    "ErrorCode",
    "ExposeConfig",
    "FlowDefinition",
    "HealthStatus",
    "JsonObject",
    "JsonSchema",
    "Layout",
    "LayoutPosition",
    "LlmCallNode",
    "LlmCallNodeConfig",
    "McpServerResource",
    "McpToolNode",
    "McpToolNodeConfig",
    "ModelProviderResource",
    "Node",
    "Page",
    "PortType",
    "RegistryEntry",
    "RegistryEntryCreate",
    "RegistryEntryPatch",
    "Resource",
    "ResourceKind",
    "RetrievalNode",
    "RetrievalNodeConfig",
    "RouterInputType",
    "RouterNode",
    "RouterNodeConfig",
    "RouterRule",
    "ScoredHit",
    "SearchBackend",
    "SearchQuery",
    "SecretsProvider",
    "Severity",
    "StartNode",
    "StartNodeConfig",
    "TemplateNode",
    "TemplateNodeConfig",
    "ToolCard",
    "ToolCardTool",
    "ValidationIssue",
    "ValidationResult",
    "VectorDBResource",
    "VectorStore",
    "agent_card_from_dict",
    "agent_card_to_json_dict",
    "input_ports",
    "output_ports",
    "ports_compatible",
    "prompt_variables",
    "render_documents",
    "serialize_card",
    "single_required_string_input",
    "split_port_ref",
    "validate_structure",
]
